version: '3.8'

services:
  products-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: products-service
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://products-postgres:5432/products
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - products-postgres
    restart: unless-stopped
  products-postgres:
    image: postgres:13
    container_name: products-postgres
    restart: always
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local